### ISSUE TITLE
Someone ripping off your content

### ISSUE THREAD

**Issue by sjwaight** [dhhruv/dhhruv#1]
Hi Dhruv - I came across some of your content being reused on a site without your permission.

Original: [Explaining Stack in Detail](https://dev.to/dhhruv/explaining-stack-in-detail-4ohm)

Copy: [Explaining Stack in Detail](https://tuts.dizzycoding.com/explaining-stack-in-detail/)

I've previously had to raise a DMCA take down request with the hosting provider Namecheap as there is no way to get in contact with the site admin otherwise. Here's their link: https://support.namecheap.com/index.php?/Tickets/Submit/RenderForm/228

**Comment by dhhruv** [comment]
> Hi Dhruv - I came across some of your content being reused on a site without your permission.
> 
> Original: [Explaining Stack in Detail](https://dev.to/dhhruv/explaining-stack-in-detail-4ohm)
> 
> Copy: [Explaining Stack in Detail](https://tuts.dizzycoding.com/explaining-stack-in-detail/)
> 
> I've previously had to raise a DMCA take down request with the hosting provider Namecheap as there is no way to get in contact with the site admin otherwise. Here's their link: https://support.namecheap.com/index.php?/Tickets/Submit/RenderForm/228

Thanks for letting me know about this @sjwaight. I'll raise a request as well regarding this issue.
